import {useState} from 'react';
import {Image,FileText,Folder,Combine,Scissors,Archive,ArrowRight,Plus,X,LoaderCircle,Check} from 'lucide-react';
import {bridge,basename,fileSize} from './bridge';
import type {Operation} from './types';
const tools=[['image','Convert images',Image],['compress','Compress images',Archive],['images-pdf','Images to PDF',FileText],['pdf-images','PDF to images',Image],['merge-pdf','Merge PDFs',Combine],['split-pdf','Split a PDF',Scissors],['extract-pdf','Extract PDF pages',FileText],['organize','Organize a folder',Folder],['cleanup','Review old files',Archive]] as const;
export function Plan({plan,onRun,onCancel,busy}:{plan:Operation;onRun:(selection:number[])=>void;onCancel:()=>void;busy:boolean}){
  const [selection,setSelection]=useState(()=>plan.items.map((_,i)=>i));
  const done=plan.items.filter(x=>x.status==='done').length;
  return <section className="plan-panel"><div className="section-heading"><div><span className="eyebrow">{busy?'IN PROGRESS':'REVIEW CHANGES'}</span><h2 className="capitalize">{plan.title}</h2></div><button className="icon-button" title="Close preview" disabled={busy} onClick={onCancel}><X size={17}/></button></div>
    <p className="panel-copy">{plan.type==='convert'?'New copies will be created. Your originals stay untouched.':plan.type==='cleanup'?'Age is only a clue. Review each file before moving it to recovery.':'Review the destination for each file. You can undo these changes later.'}</p>
    <div className="plan-list">{plan.items.map((item,i)=><div className="plan-item" key={i}><input type="checkbox" aria-label={'Include '+basename(item.from)} checked={selection.includes(i)} disabled={busy} onChange={()=>setSelection(current=>current.includes(i)?current.filter(x=>x!==i):[...current,i])}/><div><span title={item.from}>{basename(item.from)}</span><small>{fileSize(item.size)} {item.reason?' / '+item.reason:''}</small></div><ArrowRight size={13}/><div><span title={item.to}>{item.to.split(/[\\/]/).slice(-2).join(' / ')}</span><small>{item.error||item.status}</small></div></div>)}</div>
    {!plan.items.length?<p className="muted">No files match this plan.</p>:<div className="panel-actions"><span className="muted">{busy?`${done} of ${plan.items.length} complete`:`${selection.length} selected`}</span><button className="primary" disabled={!busy&&!selection.length} onClick={busy?()=>bridge.call('cancel'):()=>onRun(selection)}>{busy?<><LoaderCircle size={15} className="spin"/> Stop after current file</>:<>Confirm & run <ArrowRight size={15}/></>}</button></div>}
  </section>;
}
export default function Tools({initial,onPlan,onClose,autoConvert=false}:{initial?:string;onPlan:(p:Operation)=>void;onClose:()=>void;autoConvert?:boolean}){
  const [tool,setTool]=useState(initial||''),[files,setFiles]=useState<string[]>([]),[destination,setDestination]=useState(''),[format,setFormat]=useState('webp'),[quality,setQuality]=useState(82),[target,setTarget]=useState(0),[pages,setPages]=useState('1'),[mode,setMode]=useState('type'),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const folderTool=['organize','cleanup'].includes(tool);
  const choose=async(kind:string)=>{try{setError('');const chosen=await bridge.call('pick',{kind});if(chosen.length)setFiles(chosen);}catch(e){setError((e as Error).message);}};
  const create=async()=>{setBusy(true);setError('');try{const options={tool,files,destination,folder:files[0],format,quality,targetKB:target,pages:pages.split(',').map(x=>Number(x.trim())),mode};onPlan(await bridge.call('tool-plan',options));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <section className="tools-panel"><div className="section-heading"><div className="heading-group">{tool&&<button className="icon-button" title="All tools" onClick={()=>{setTool('');setFiles([]);}}><ArrowRight className="back-arrow" size={16}/></button>}<h2>{tools.find(x=>x[0]===tool)?.[1]||'File tools'}</h2></div><button className="icon-button" title="Close tools" onClick={onClose}><X size={18}/></button></div>
    {!tool?<div className="tool-grid">{tools.map(([id,title,Icon])=><button className="tool-tile" key={id} onClick={()=>setTool(id)}><Icon size={20}/><span>{title}</span><ArrowRight size={14}/></button>)}</div>:<>
      <button className="file-drop" onClick={()=>choose(folderTool?'folder':['image','compress','images-pdf'].includes(tool)?'images':'pdf')}><Plus size={21}/><span>{files.length?`${files.length} selected`:`Choose ${folderTool?'a folder':tool==='images-pdf'?'images':tool.includes('pdf')?'PDF files':'images'}`}</span>{files.length>0&&<small>{files.map(basename).slice(0,3).join(', ')}</small>}</button>
      {!folderTool&&<label className="field-label">Save to<button className="folder-choice" onClick={async()=>{try{const [folder]=await bridge.call('pick',{kind:'folder'});if(folder)setDestination(folder);}catch(e){setError((e as Error).message);}}}><Folder size={16}/><span>{destination||'Choose an output folder'}</span><Chevron/></button></label>}
      {['image','compress'].includes(tool)&&<><div className="form-grid"><label className="field-label">Format<select value={format} onChange={e=>setFormat(e.target.value)}>{['jpeg','png','webp','avif','gif','tiff'].map(x=><option key={x} value={x}>{x.toUpperCase()}</option>)}</select></label><label className="field-label">Target size (KB)<input type="number" min="0" max="100000" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label></div><label className="field-label">Quality <span className="muted">{quality}%</span><input type="range" min="10" max="100" value={quality} onChange={e=>setQuality(Number(e.target.value))}/></label><p className="muted small">Target size is best effort. 0 keeps quality-based sizing.</p></>}
      {tool==='extract-pdf'&&<label className="field-label">Pages<input value={pages} onChange={e=>setPages(e.target.value)} placeholder="1, 2, 5"/></label>}
      {tool==='organize'&&<label className="field-label">Group files by<select value={mode} onChange={e=>setMode(e.target.value)}><option value="type">File type</option><option value="month">Modification month</option></select></label>}
      <div className="panel-actions"><span className="muted small">{folderTool?'Preview before changing anything.':'Originals are preserved.'}</span><button className="primary" disabled={busy||!files.length||!folderTool&&!destination} onClick={create}>{busy?<LoaderCircle className="spin" size={16}/>:<>{autoConvert&&!folderTool?'Create outputs':'Preview changes'} <ArrowRight size={15}/></>}</button></div>
    </>}
    {error&&<p className="inline-error" role="alert">{error}</p>}
  </section>;
}
function Chevron(){return <ArrowRight size={14}/>;}
